[format]
indent = 4
max_line_length = 90
sort_imports = true
sort_inputs = false
trailing_commas = true
newline_style = "unix"

[check]
deny_warnings = true
deny_notes = true
tags = ["all"]

[check.lint]
bash_set_options = ["errexit", "nounset", "pipefail"]
